AdminApplications/Controllers/MemberListController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AdminApplicationsLibrary;
using AdminApplications.DAL;
using AdminApplications.Models;
using System.Net;


namespace AdminApplications.Controllers
{
    [Authorize]
    public class MemberListController : Controller
    {
        private MemberListViewModelRepository memberListViewModelRepository;
       
        public MemberListController()
        {
            this.memberListViewModelRepository = new MemberListViewModelRepository();
        }

        public MemberListController(MemberListViewModelRepository memberListViewModelRepository)
        {
            this.memberListViewModelRepository = memberListViewModelRepository;
        }

        // GET: Member
        public ActionResult Index()
        {
            var memberListViewModels = memberListViewModelRepository.Fill().OrderBy(ml=>ml.last_name);
            ViewBag.Title = "View Members";
            return View("Index", memberListViewModels);
        }

        // GET: Member
        public ActionResult Leadership()
        {
            var memberListViewModels = memberListViewModelRepository.GetAllLeadership().OrderBy(ml => ml.last_name);
            ViewBag.Title = "View Leadership"; 
            return View("Index", memberListViewModels);
        }

        // GET: Member
        public ActionResult ResearchInterest()
        {
            var memberListViewModels = memberListViewModelRepository.GetAllResearch().OrderBy(ml => ml.last_name);
            ViewBag.Title = "View Research Interests";
            return View("Index", memberListViewModels);
        }

        // GET: Member
        public ActionResult Edit(int? id)
        {
            if (id != null)
                {
                    var member = new MemberListEditViewModel(id);
                    if (member != null)
                        {
                            TempData["memberId"] = id;
                            return View("Edit", member);
                        }
                    return HttpNotFound();
                }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }


    }
}

AdminApplications/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Admin Applications</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/kendo/css")
    @Scripts.Render("~/bundles/kendo")
    <link rel="stylesheet" type="text/css" href="~/Content/Styles/banner.css">
    <link rel="stylesheet" href="~/Content/font-awesome.css">
    @RenderSection("JavaScript", required: false)
	<script src="@Url.Content("~/Scripts/kendo/2015.3.930/jszip.min.js")"></script>
</head>
<body>
    <div class="masthead" id="bannerdiv">
        <img id="banner" src="~/Content/Images/Banner.png" />
    </div>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administration", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Membership Lists<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Membership", "Index", "MemberList")</li>
                            <li>@Html.ActionLink("Leadership", "Leadership", "MemberList")</li>
                            <li>@Html.ActionLink("Research Interest", "ResearchInterest", "MemberList")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Comprehensive Cancer Center</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>